# Base image
FROM node:16
# Make folder to put our files in
RUN mkdir -p /usr/src/freestream
RUN mkdir -p /usr/src/freestream/frontend
# Set working directory so that all
# subsequent command runs in this folder
WORKDIR /usr/src/freestream/frontend
# Copy package json and install dependencies
COPY package*.json ./
RUN npm install
# Copy our app
COPY . .
# Expose port to access server
EXPOSE 3000
EXPOSE 5173
# Command to run our app
CMD [ "npm", "run", "dev" ]
COPY . /home/svelte/front